version: '3'
services:
    cv:
      build:
        context: .
        dockerfile: Dockerfile
        target: release
      volumes:  
        - cv:/opt/app
    web:
      depends_on:
      - cv
      image: nginx:1.23-alpine
      ports: 
      - 8080:80
      volumes:
       - ./config/nginx/web.config:/etc/nginx/conf.d/default.conf
       - cv:/usr/share/nginx/html
volumes: 
  cv: